# Generated by Django 2.1.7 on 2019-03-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_folders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='title',
            new_name='folder_title',
        ),
    ]
