# Generated by Django 2.1.7 on 2019-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_folders', '0004_auto_20190314_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='programs',
            field=models.ManyToManyField(blank=True, to='user_folders.Program'),
        ),
    ]
